####################################################
#efficiency simulation for GeMSE
####################################################

#write primaries to root file
/writePrimaries false

#z-position of end cap = 3.95cm
#z-position of center of sample cavity = 7.94cm

/gps/pos/type Volume
/gps/pos/shape Para

#sample position 
/gps/pos/centre 0 0 7.94 cm

#sample size
/gps/pos/halfx 12. cm
/gps/pos/halfy 12. cm
/gps/pos/halfz 17.5 cm

/gps/pos/confine sample

/gps/energy 0 keV
/gps/particle ion


##############################
#simulate gammas only
##############################
/gps/particle gamma
/gps/ang/type iso

#Pa234m (gammas)
/gammaline/energy 1001.0 
/gammaline/G4BR 1 
/gammaline/NuDatBR 0.00842 
/gammaline/SigRegion 0.4 
/gammaline/BkgRegion 10.

/gps/energy 1001 keV
/run/beamOn 100000

#Th234 (gammas)
/gammaline/energy 63.3 
/gammaline/G4BR 1 
/gammaline/NuDatBR 0.037 
/gammaline/SigRegion 0.4 
/gammaline/BkgRegion 10.

/gps/energy 63.3 keV
/run/beamOn 100000

/gammaline/energy 92.6 
/gammaline/G4BR 1 
/gammaline/NuDatBR 0.0423 
/gammaline/SigRegion 1.2 
/gammaline/BkgRegion 10.

/gps/energy 92.6 keV
/run/beamOn 100000

##############################
#switch to full decays
##############################
/gps/energy 0 keV
/gps/particle ion

#Pb214
/gammaline/energy 295.2 
/gammaline/G4BR 0.18746 
/gammaline/NuDatBR 0.1842
/gammaline/SigRegion 0.4 
/gammaline/BkgRegion 10.

/gammaline/energy 351.9 
/gammaline/G4BR 0.3688 
/gammaline/NuDatBR 0.3560
/gammaline/SigRegion 0.4 
/gammaline/BkgRegion 10.

/gps/ion 82 214 0 0
/grdm/nucleusLimits 214 214 82 82 
/run/beamOn 100000