#Select general particle source
/gun/select gps

#write primaries to root file
/writePrimaries false

#Sample position in cm
/gps/position 0 0 0

/gps/pos/type Volume
/gps/pos/shape Para

#Sample size
/gps/pos/halfx 0.5 m
/gps/pos/halfy 0.5 m 
/gps/pos/halfz 0.5 m

/gps/energy 0 keV
/gps/particle ion

/grdm/noVolumes
/grdm/selectVolume expHall_log

#visualization
#/control/execute vis.mac
#/vis/viewer/set/viewpointThetaPhi 90 90


#Rn222
/gps/ion 86 222 0 0
/run/beamOn 10000000
